substitutions:
  device_base_name: "dht22-esp01"
  device_friendly_name: "DHT22 ESP-01"
  setup_ap_ssid: "DHT22 ESP01 Setup"

esphome:
  name: ${device_base_name}
  name_add_mac_suffix: true
  friendly_name: ${device_friendly_name}
  project:
    name: "hugo-leij.dht22-esp01"
    version: "1.0.0"

esp8266:
  board: esp01_1m

logger:

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  - platform: http_request
    id: ota_http

http_request:
  verify_ssl: false

web_server:
  version: 2
  port: 80

update:
  - platform: http_request
    name: "Firmware Update"
    source: https://raw.githubusercontent.com/hugo-leij/esphome-dht22-esp01/main/manifest.json

wifi:
  fast_connect: true
  power_save_mode: none

  ap:
    ssid: ${setup_ap_ssid}

captive_portal:

number:
  - platform: template
    name: "Temperature Offset"
    id: temperature_offset
    min_value: -10
    max_value: 10
    step: 0.1
    mode: box
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 0.0
    entity_category: config

  - platform: template
    name: "Humidity Offset"
    id: humidity_offset
    min_value: -20
    max_value: 20
    step: 0.1
    mode: box
    unit_of_measurement: "%"
    optimistic: true
    restore_value: true
    initial_value: 0.0
    entity_category: config

sensor:
  - platform: dht
    pin: GPIO2
    model: DHT22
    temperature:
      name: "Temperature"
      id: temperature
      device_class: temperature
      state_class: measurement
      filters:
        - lambda: return x + id(temperature_offset).state;
    humidity:
      name: "Humidity"
      id: humidity
      device_class: humidity
      state_class: measurement
      filters:
        - lambda: return x + id(humidity_offset).state;
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: 60s
    icon: "mdi:wifi"

  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    icon: "mdi:timer-outline"

binary_sensor:
  - platform: status
    name: "Status"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      entity_category: diagnostic
      icon: "mdi:ip-network"
    ssid:
      name: "SSID"
      entity_category: diagnostic
      icon: "mdi:wifi-settings"

button:
  - platform: restart
    name: "Restart device"
    icon: "mdi:restart"